### PR TITLE
User dashboard header

### LINKED ISSUE #60: Frontend header for accounts dashboard
Make header same as employee dashboard and add logout functionality

### PR DESCRIPTION
**Pull request by runimari**
Modified the accounts_dashboard to have the same header as employee screen, with logout and profile button. 
Edited userdashboard.css to have necessary styles-- added header classes and changed nav bar styles.
Added icons next to links in nav bar.
Closes #60

### CODE REVIEW

**Comment by ericz9002** [comment]
I think centering the accounts would make it look better, unless you are planning to add more stuff on the right side

**Comment by ab235** [comment]
looks fine for now

**Review by ab235 — APPROVED** [review]

**Comment by SharpBit** [comment]
> looks fine for now - given that our beta says we need something for credit cards, its probs fine to leave it

We are allowed to drop credit card support as it would be extremely difficult to implement all our originally promised features by Tuesday's demo. They said to just write which features we will include in our Beta release deliverables

**Review by ericz9002 — APPROVED** [review]

**Review by SharpBit — CHANGES_REQUESTED** [review]
transfer and transactions page also need to be updated with this new header

**Review by SharpBit — APPROVED** [review]

**Review by skara9 — APPROVED** [review]

**Pull request merged**
